/*
 * generated by Xtext 2.12.0
 */
package de.upb.mbse.taxcalculationexample.ide


/**
 * Use this class to register ide components.
 */
class TaxCalculationRulesIdeModule extends AbstractTaxCalculationRulesIdeModule {
}
